name: plantyze
description: A Flutter app for plant identification using camera recognition.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^6.0.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
